### ISSUE TITLE
Could not find bone: rightArm

### ISSUE THREAD

**Issue by emyfops** [eehunter/RiseOfTheToasters#2]
Version: 1.17.1
Steps to reproduce:

Enter a singleplayer world
Press Y
Put a basic cybernetic arm
Press f5
crash

**Comment by eehunter** [comment]
This is a known issue cause by the fact that limb rendering gave me trouble and I never bothered to get it working. Versions prior to the "Limb Rendering Part 1" commit shouldn't have this issue. Most of the code in this repo will have to be rewritten to integrate FurLib and Apoli, which should make the mod significantly more stable in the long run.

**Comment by emyfops** [comment]
Also quick question, will you work on 1.17 or 1.18 for the mod?
I have a modded server with other protogens and we would love to have the mod ready for 1.17/1.18

**Comment by eehunter** [comment]
My time for programming is limited, but my goal is to make the code for both FurLib and RotT as version agnostic as possible (by way of using existing libraries wherever I can), which should make porting them fairly trivial. A warning though, the 1.17+ versions will not be compatible with the 1.16.5 legacy versions, as the way that the limb system works is completly different, and I don't have time to make a system to convert stuff automatically. If you're just looking for the aesthetic portion, FurLib can provide that, and is nearly ready for an initial release (it should be usable in it's current state, I just have to do testing and make sure everything is ready).
